version: "2"
services:

  vault:
    image: vault:0.9.3
    ports:
      - "${VAULT_PORT}:8200"
    links:
      - postgresql
    environment:
      SKIP_SETCAP: "true"
      VAULT_DEV_ROOT_TOKEN_ID: 'dev-token'
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:${VAULT_PORT}

  postgresql:
    image: postgres:alpine
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    volumes:
      - ./build/postgres/:/docker-entrypoint-initdb.d/

  sqs:
    image: 288840537196.dkr.ecr.eu-west-2.amazonaws.com/tech.form3/elasticmq
    ports:
      - "${SQS_PORT}:9324"
    volumes:
      - ./build/sqs/queues.conf:/queues.conf


#  pact-go:
#    image: erecarte/go-pact-daemon-docker
#    ports:
#      - "${PACT_GO_PORT}:6666"
#
#  pact-stubs:
#    image: pactfoundation/pact-mock-service
#    ports:
#      - "${PACT_SERVER_PORT}:80"
#    volumes:
#      - "./build/pacts:/app/pacts"
#    command: "bundle exec pact-mock-service service --port 1234 --consumer Foo --provider Bar --pact-specification-version 2 --pact-dir /app/pacts"
#    command: "--pact-dir=/app/pacts --port 8080"



  pact-stubs:
    image: pactfoundation/pact-stub-server
    ports:
      - "${PACT_SERVER_PORT}:8080"
    volumes:
      - "./build/pacts:/app/pacts"
    command: "--dir=/app/pacts --port 8080"

  wiremock:
    image: rodolpheche/wiremock
    ports:
     - "${WIREMOCK_PORT}:8080"
    command: '--proxy-all="http://pact-stubs:8080"'

  dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - postgresql
      - vault
      - sqs
    links:
      - postgresql
      - vault
      - sqs
    command: postgresql:${POSTGRES_PORT} vault:${VAULT_PORT} sqs:${SQS_PORT}

  fake-ets:
    image: 288840537196.dkr.ecr.eu-west-1.amazonaws.com/tech.form3/fake-ets
    ports:
      - "${FAKE_ETS_PORT}:8119"

  indoor-terraform:
    image: 288840537196.dkr.ecr.eu-west-1.amazonaws.com/tech.form3/api-indoor-terraform:develop
    depends_on:
      - dependencies
    links:
      - postgresql
      - vault
    environment:
        VAULT_ADDR: http://vault:${VAULT_PORT}
        VAULT_TOKEN: 'dev-token'
        STACK_NAME: local
        ENVIRONMENT: development
        STARLING_SHARED_SECRET: secret
        DATABASE_USER: root
        DATABASE_PASSWORD: password
        DATABASE_ADDRESS: postgresql

