version: "2"
services:

  vault:
    image: vault:0.9.3
    ports:
      - "${VAULT_PORT}:8200"
    links:
      - postgresql
    environment:
      SKIP_SETCAP: "true"
      VAULT_DEV_ROOT_TOKEN_ID: 'dev-token'
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:${VAULT_PORT}

  postgresql:
    image: postgres:alpine
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    volumes:
      - ./build/postgres/:/docker-entrypoint-initdb.d/
