[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"

[[constraint]]
  name = "github.com/docker/libcompose"
  revision = "57bd716502dcbe1799f026148016022b0f3b989c"

[[override]]
  name = "github.com/docker/docker"
  revision = "7848b8beb9d38a98a78b75f78e05f8d2255f9dfe"

[[override]]
  name = "github.com/docker/cli"
  revision = "3352c0e137e80b7e10fb0efc9812df7bca9497a2"

[[override]]
  name = "github.com/docker/distribution"
  revision = "edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c"

[[override]]
  name = "github.com/docker/go-connections"
  revision = "3ede32e2033de7505e6500d6c868c2b9ed9f169d"

[[override]]
  name = "github.com/docker/go-units"
  revision = "9e638d38cf6977a37a8ea0078f3ee75a7cdb2dd1"

[[override]]
  name = "github.com/xeipuuv/gojsonschema"
  revision = "0c8571ac0ce161a5feb57375a9cdf148c98c0f70"

[prune]
  go-tests = true
  unused-packages = true
